### ISSUE TITLE
Confirm MEND model configuration

### ISSUE THREAD

**Issue by kdorheim** [Microbial-Explicit-Model/MEMC#18]
Right now the the implementation of MEND in our package uses the following configuration. 

|model |DOMuptake |POMdecomp |MBdecay |
|:-----|:---------|:---------|:-------|
|MEND  |MM        |MM        |LM      |

1) We need to confirm that this the correct combination of the dynamics. 

2) Also confirm that this is the correct reference 

Wang, G., Post, W. M., and Mayes, M. A.: Development of microbial-enzyme-mediated decomposition model parameters through steady-state and dynamic analyses, Ecol. Appl., 23, 255–272, 2013.

**Comment by jianqiuz** [comment]
Yes correct.
