### ISSUE TITLE
What software did you use to make figures? Where are files?

### ISSUE THREAD

**Issue by bpbond** [Microbial-Explicit-Model/MEMC#34]
![pool_structure](https://github.com/user-attachments/assets/355d8332-21ed-43fe-82f1-2a68fdd3d7a9)

**Comment by kdorheim** [comment]
I made them in [slides](https://docs.google.com/presentation/d/11DkKwksMh-flFzixZ_KYQOrs_xJmr2CIixIG63qmmSg/edit?usp=sharing) I can share with your gmail
