### ISSUE TITLE
Have a function that returns all available models?

### ISSUE THREAD

**Issue by bpbond** [Microbial-Explicit-Model/MEMC#36]
In `ModelComparison.Rmd`:

```r
# Solve all the model configurations. 
out1 <- solve_model(mod = MEND_model, time = times)
out2 <- solve_model(mod = COMISSION_model, time = times)
out3 <- solve_model(mod = CORPSE_model, time = times)
out4 <- solve_model(mod = MEMS_model, time = times)
out5 <- solve_model(mod = BAMS_model, time = times)
out6 <- solve_model(mod = MIMCS_model, time = times)
```
Two issues here:

* Code repetition (this is minor); and
* If we add/subtract package models, this will break.

What do you think about providing a function `memc_models()` or similar, that returns a list of available models? Then we could do something like

```r
mods <- memc_models()
out <- lapply(mods, solve_model, time = times)
# proceed to rbind the results...
```

**Comment by kdorheim** [comment]
That is a good idea right now the object `model_configs` returns a summary table of all configurations supported. Do you think having it be a function would make it more user-friendly? re the option to do the multiple model runs I like it and will noodle on it a bit. 

```
> model_configs
      model DOMuptake POMdecomp MBdecay
1      MEND        MM        MM      LM
2 COMISSION        MM       RMM      LM
3    CORPSE       RMM        LM      LM
4      MEMS        LM        LM      LM
5      BAMS        MM        MM      LM
6     MIMCS        MM        MM      DD
```

**Comment by bpbond** [comment]
Sounds good. Thanks.

>Do you think having it be a function would make it more user-friendly

Probably not a huge difference...but if it's a function, it can build the summary table from `memc_models()`, so if one of them is changed, the summary table gets updated automatically.
